version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: league/flysystem
    versions:
    - 2.0.2
    - 2.0.3
    - 2.0.4
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
